# This is a generated file. Not intended for manual editing.
services:
  api:
    build:
      context: "/home/klappo/workspace/learn/KitchenHell"
      dockerfile: "./src/KitchenHell.Api/Dockerfile"
      target: "build"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/KitchenHell.Api.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "kitchenhell-api:dev"
    ports: []
    volumes:
    - "/home/klappo/.nuget/packages:/root/.nuget/packages"
    - "/home/klappo/workspace/learn/KitchenHell/src/KitchenHell.Api:/app:rw"
    - "/home/klappo/workspace/learn/KitchenHell:/src:rw"
    working_dir: "/app"
